# Generated by Django 4.1.7 on 2023-04-03 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie', '0004_moviereview_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviereview',
            name='user',
        ),
        migrations.AddField(
            model_name='moviereview',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
