# Generated by Django 4.1.7 on 2023-04-18 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_streamplatform_movie_stream_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailablePlatformsMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='streamplatform',
            name='available_movie',
            field=models.ManyToManyField(to='movie.availableplatformsmovie'),
        ),
    ]
