# Generated by Django 4.1.7 on 2023-04-26 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_availableplatformsmovie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviereview',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
