# Generated by Django 4.1.7 on 2023-04-26 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_moviereview_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviereview',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
